In [185]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [186]:
df=pd.read_csv("/content/train.csv")

In [187]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [188]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [189]:
df.dropna(subset=['Embarked'],inplace=True)

NAME

In [190]:
df["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 889, dtype: object

In [191]:
df["Title"]=df["Name"].str.split(',').str[1].str.split('.').str[0]  #Extract Title from Name

In [192]:
df["Fname"]=df["Name"].str.split(",").str[0]

In [193]:
df["Lname"]=df["Name"].str.split(",").str[1].str.split(" ").str[-1]

In [194]:
df["Lname"]=df['Lname'].str.extract(r"([A-Za-z]+)")

In [195]:
df.drop_duplicates()
df.shape

(889, 15)

In [196]:
df.drop(["Name", "Ticket", "PassengerId"], axis=1, inplace=True)

Sex

In [197]:
'''df["Sex"]=df["Sex"].str.lower()
df["Sex"]=df["Sex"].map({"male":1,"female":0})
print(df["Sex"])  '''

# ONE HOT Encoding
df=pd.get_dummies(df,columns=["Sex"])
df.columns

Index(['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Cabin',
       'Embarked', 'Title', 'Fname', 'Lname', 'Sex_female', 'Sex_male'],
      dtype='object')

In [198]:
df['Title'].unique()

array([' Mr', ' Mrs', ' Miss', ' Master', ' Don', ' Rev', ' Dr', ' Mme',
       ' Ms', ' Major', ' Lady', ' Sir', ' Mlle', ' Col', ' Capt',
       ' the Countess', ' Jonkheer'], dtype=object)

In [199]:
df['Title']=df['Title'].replace(["the Countess"],"Countess")

In [200]:
df['Title']=df['Title'].str.strip()
df['Title'].unique()

array(['Mr', 'Mrs', 'Miss', 'Master', 'Don', 'Rev', 'Dr', 'Mme', 'Ms',
       'Major', 'Lady', 'Sir', 'Mlle', 'Col', 'Capt', 'the Countess',
       'Jonkheer'], dtype=object)

In [201]:
#print count of particular value
df.loc[df['Title']=="Mrs",'Title'].value_counts()

Title
Mrs    124
Name: count, dtype: int64

AGE

In [202]:
df['Age'].skew()  #-> approx normal dist->use mean
df['Age']=df['Age'].fillna(df['Age'].mean())

In [203]:
#OULIER HANDLING -AGE

q1=df['Age'].quantile(0.25)
q3=df['Age'].quantile(0.75)
iqr=q3-q1

lb=q1-1.5*iqr
ub=q3+1.5*iqr

df['Age']=df["Age"].clip(lb,ub)

In [204]:
df.head()

,Survived,Pclass,Age,SibSp,Parch,Fare,Cabin,Embarked,Title,Fname,Lname,Sex_female,Sex_male
0,0,3,22.0,1,0,7.2500,NaN,S,Mr,Braund,Harris,False,True
1,1,1,38.0,1,0,71.2833,C85,C,Mrs,Cumings,Thayer,True,False
2,1,3,26.0,0,0,7.9250,NaN,S,Miss,Heikkinen,Laina,True,False
3,1,1,35.0,1,0,53.1000,C123,S,Mrs,Futrelle,Peel,True,False
4,0,3,35.0,0,0,8.0500,NaN,S,Mr,Allen,Henry,False,True

CABIN-Extract Deck from Cabin

In [205]:
df['Cabin'].value_counts()

Cabin
C23 C25 C27    4
G6             4
B96 B98        4
F33            3
E101           3
              ..
E17            1
A24            1
C50            1
B42            1
C148           1
Name: count, Length: 146, dtype: int64

In [206]:
df['Cabin'].isnull().sum()

np.int64(687)

In [207]:
df['Cabin']=df['Cabin'].fillna("Unknown")

In [208]:
df['Cabin']=df['Cabin'].str[0]
df['Cabin']=df['Cabin'].replace('T','U')
df['Cabin'].value_counts()

Cabin
U    688
C     59
B     45
D     33
E     32
A     15
F     13
G      4
Name: count, dtype: int64

In [209]:
#ONE Hot encoding
df=pd.get_dummies(df,columns=["Cabin"])

In [210]:
df.columns

Index(['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked',
       'Title', 'Fname', 'Lname', 'Sex_female', 'Sex_male', 'Cabin_A',
       'Cabin_B', 'Cabin_C', 'Cabin_D', 'Cabin_E', 'Cabin_F', 'Cabin_G',
       'Cabin_U'],
      dtype='object')

In [211]:
df.head()

,Survived,Pclass,Age,SibSp,Parch,Fare,Embarked,Title,Fname,Lname,Sex_female,Sex_male,Cabin_A,Cabin_B,Cabin_C,Cabin_D,Cabin_E,Cabin_F,Cabin_G,Cabin_U
0,0,3,22.0,1,0,7.2500,S,Mr,Braund,Harris,False,True,False,False,False,False,False,False,False,True
1,1,1,38.0,1,0,71.2833,C,Mrs,Cumings,Thayer,True,False,False,False,True,False,False,False,False,False
2,1,3,26.0,0,0,7.9250,S,Miss,Heikkinen,Laina,True,False,False,False,False,False,False,False,False,True
3,1,1,35.0,1,0,53.1000,S,Mrs,Futrelle,Peel,True,False,False,False,True,False,False,False,False,False
4,0,3,35.0,0,0,8.0500,S,Mr,Allen,Henry,False,True,False,False,False,False,False,False,False,True

In [212]:
df.drop(["Fname","Lname"],axis=1,inplace=True)

In [213]:
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [214]:
df=pd.get_dummies(df,columns=["Embarked"])
df.columns

Index(['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Title',
       'Sex_female', 'Sex_male', 'Cabin_A', 'Cabin_B', 'Cabin_C', 'Cabin_D',
       'Cabin_E', 'Cabin_F', 'Cabin_G', 'Cabin_U', 'Embarked_C', 'Embarked_Q',
       'Embarked_S'],
      dtype='object')

In [215]:
df["Title"].value_counts()

Title
Mr              517
Miss            181
Mrs             124
Master           40
Dr                7
Rev               6
Col               2
Mlle              2
Major             2
Ms                1
Mme               1
Don               1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [216]:
rare_list = [
    "Dr", "Rev", "Col", "Mlle", "Major",
    "Ms", "Mme", "Don", "Lady", "Sir",
    "Capt", "the Countess", "Jonkheer"
]

In [217]:
df["Title"] = df["Title"].replace(rare_list, "Rare")

In [218]:
df=pd.get_dummies(df,columns=["Title"])
df.columns

Index(['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_female',
       'Sex_male', 'Cabin_A', 'Cabin_B', 'Cabin_C', 'Cabin_D', 'Cabin_E',
       'Cabin_F', 'Cabin_G', 'Cabin_U', 'Embarked_C', 'Embarked_Q',
       'Embarked_S', 'Title_Master', 'Title_Miss', 'Title_Mr', 'Title_Mrs',
       'Title_Rare'],
      dtype='object')

In [219]:
df.head()

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Cabin_A,Cabin_B,...,Cabin_G,Cabin_U,Embarked_C,Embarked_Q,Embarked_S,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Rare
0,0,3,22.0,1,0,7.2500,False,True,False,False,...,False,True,False,False,True,False,False,True,False,False
1,1,1,38.0,1,0,71.2833,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False
2,1,3,26.0,0,0,7.9250,True,False,False,False,...,False,True,False,False,True,False,True,False,False,False
3,1,1,35.0,1,0,53.1000,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False
4,0,3,35.0,0,0,8.0500,False,True,False,False,...,False,True,False,False,True,False,False,True,False,False

In [220]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Survived      889 non-null    int64
 1   Pclass        889 non-null    int64
 2   Age           889 non-null    float64
 3   SibSp         889 non-null    int64
 4   Parch         889 non-null    int64
 5   Fare          889 non-null    float64
 6   Sex_female    889 non-null    bool
 7   Sex_male      889 non-null    bool
 8   Cabin_A       889 non-null    bool
 9   Cabin_B       889 non-null    bool
 10  Cabin_C       889 non-null    bool
 11  Cabin_D       889 non-null    bool
 12  Cabin_E       889 non-null    bool
 13  Cabin_F       889 non-null    bool
 14  Cabin_G       889 non-null    bool
 15  Cabin_U       889 non-null    bool
 16  Embarked_C    889 non-null    bool
 17  Embarked_Q    889 non-null    bool
 18  Embarked_S    889 non-null    bool
 19  Title_Master  889 non-null    bool
 20  Title_Miss    889 non-null    bool
 21  Title_Mr      889 non-null    bool
 22  Title_Mrs     889 non-null    bool
 23  Title_Rare    889 non-null    bool
dtypes: bool(18), float64(2), int64(4)
memory usage: 64.2 KB

In [223]:
y=df['Survived']
X=df.drop("Survived",axis=1)
print(X.shape,y.shape)
print(y.head())

(889, 23) (889,)
0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

TRAIN TEST SPLIT AND SCALING

In [226]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

X = df.drop("Survived", axis=1)
y = df["Survived"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
c = ["Age", "Fare"]
X_train[c] = scaler.fit_transform(X_train[c])
X_test[c] = scaler.transform(X_test[c])

In [227]:
X_train.head()

,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Cabin_A,Cabin_B,Cabin_C,...,Cabin_G,Cabin_U,Embarked_C,Embarked_Q,Embarked_S,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Rare
708,1,-0.618788,0,0,2.430597,True,False,False,False,False,...,False,True,False,False,True,False,True,False,False,False
240,3,0.008677,1,0,-0.358135,True,False,False,False,False,...,False,True,True,False,False,False,True,False,False,False
382,3,0.202277,0,0,-0.490949,False,True,False,False,False,...,False,True,False,False,True,False,False,True,False,False
792,3,0.008677,8,2,0.762595,True,False,False,False,False,...,False,True,False,False,True,False,True,False,False,False
683,3,-1.275640,5,2,0.301860,False,True,False,False,False,...,False,True,False,False,True,False,False,True,False,False

In [228]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [229]:
y_predict=model.predict(X_test)

In [230]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.87      0.84      0.86       109
           1       0.76      0.80      0.78        69

    accuracy                           0.83       178
   macro avg       0.82      0.82      0.82       178
weighted avg       0.83      0.83      0.83       178